
package com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Logger", targetNamespace = "http://service.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Logger {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.com/", className = "com.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.com/", className = "com.AddResponse")
    @Action(input = "http://service.com/Logger/addRequest", output = "http://service.com/Logger/addResponse")
    public Boolean add(
        @WebParam(name = "arg0", targetNamespace = "")
        Log arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.com/", className = "com.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.com/", className = "com.DeleteResponse")
    @Action(input = "http://service.com/Logger/deleteRequest", output = "http://service.com/Logger/deleteResponse")
    public Boolean delete(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "getLog", targetNamespace = "http://service.com/", className = "com.GetLog")
    @ResponseWrapper(localName = "getLogResponse", targetNamespace = "http://service.com/", className = "com.GetLogResponse")
    @Action(input = "http://service.com/Logger/getLogRequest", output = "http://service.com/Logger/getLogResponse")
    public void getLog(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://service.com/", className = "com.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://service.com/", className = "com.PingResponse")
    @Action(input = "http://service.com/Logger/pingRequest", output = "http://service.com/Logger/pingResponse")
    public String ping();

}
