
package com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Logger", targetNamespace = "http://service.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Logger {


    /**
     * 
     * @param logType
     * @param moduleName
     * @param description
     * @param platform
     * @param statusCode
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://service.com/", className = "com.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.com/", className = "com.AddResponse")
    @Action(input = "http://service.com/Logger/addRequest", output = "http://service.com/Logger/addResponse")
    public Boolean add(
        @WebParam(name = "description", targetNamespace = "")
        String description,
        @WebParam(name = "logType", targetNamespace = "")
        int logType,
        @WebParam(name = "moduleName", targetNamespace = "")
        String moduleName,
        @WebParam(name = "statusCode", targetNamespace = "")
        int statusCode,
        @WebParam(name = "platform", targetNamespace = "")
        int platform);

    /**
     * 
     * @param dateTo
     * @param dateFrom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLogByRange", targetNamespace = "http://service.com/", className = "com.GetLogByRange")
    @ResponseWrapper(localName = "getLogByRangeResponse", targetNamespace = "http://service.com/", className = "com.GetLogByRangeResponse")
    @Action(input = "http://service.com/Logger/getLogByRangeRequest", output = "http://service.com/Logger/getLogByRangeResponse")
    public String getLogByRange(
        @WebParam(name = "dateFrom", targetNamespace = "")
        String dateFrom,
        @WebParam(name = "dateTo", targetNamespace = "")
        String dateTo);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://service.com/", className = "com.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://service.com/", className = "com.PingResponse")
    @Action(input = "http://service.com/Logger/pingRequest", output = "http://service.com/Logger/pingResponse")
    public String ping();

    /**
     * 
     * @param date
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLog", targetNamespace = "http://service.com/", className = "com.GetLog")
    @ResponseWrapper(localName = "getLogResponse", targetNamespace = "http://service.com/", className = "com.GetLogResponse")
    @Action(input = "http://service.com/Logger/getLogRequest", output = "http://service.com/Logger/getLogResponse")
    public String getLog(
        @WebParam(name = "date", targetNamespace = "")
        String date);

}
